version: '3' 

services:
  web:
    container_name: resize_movie_sample
    build: 
      context: ./docker-config  # Dockerfileのあるディレクトリへの相対パスを指定
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes: 
      - ./:/var/www/html